[app]
name = "demo"
host = "0.0.0.0"
port = "8050"
key = "this is you app key"

[mysql]
host = "127.0.0.1"
port = "3306"
username = "root"
password = "123456"
database = "test"

[log]
level = "debug"
dir = "logs"
format = "text"
to = "stdout"